name: Meteor CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: meteorengineer/setup-meteor@test
    - name: Test
      run: |
        meteor npm install
        meteor npm test
